<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'nunito' => array(
    '200_italic' => $fontDir . '/nunito-200-italic_f6d0e68c27be7b625e489f9420785870',
    '300_italic' => $fontDir . '/nunito-300-italic_41c29151b3e3fcb095eda6cf07bcd6e6',
    'italic' => $fontDir . '/nunito-italic_d5eb7be3a33f3982a164ece68cc78ac8',
    '600_italic' => $fontDir . '/nunito-600-italic_43379e8fc995479d0270da3b4913ddf6',
    'bold_italic' => $fontDir . '/nunito-bold-italic_a1bac650e8b26fd9b12929ca4c3bcee0',
    '800_italic' => $fontDir . '/nunito-800-italic_0e562124e7e10054ad097d03d098375f',
    '900_italic' => $fontDir . '/nunito-900-italic_1fa47b0f8a87b7547ca2f739d99a94fd',
    '200' => $fontDir . '/nunito-200_bd9c1a842531b8bf254ce84d58e5f9de',
    '300' => $fontDir . '/nunito-300_aa5a2890f83ac6eed5c0177ed301438e',
    'normal' => $fontDir . '/nunito-normal_e93b6d41bf8c134cda18812cdd2254ab',
    '600' => $fontDir . '/nunito-600_73b151ac4ce1e8549893c41bab5e2c7a',
    'bold' => $fontDir . '/nunito-bold_52aee9255c99b957f975c6a2d273de94',
    '800' => $fontDir . '/nunito-800_f63f2ec8ab2bdc2c981d084d4c7af7e7',
    '900' => $fontDir . '/nunito-900_ac459ba8f7b66a7ccc7d818ff63946d1',
  ),
  'font awesome 5 brands' => array(
    'normal' => $fontDir . '/font-awesome-5-brands-normal_c16b32a721a173cf95f5028e15949eac',
  ),
  'font awesome 5 free' => array(
    'normal' => $fontDir . '/font-awesome-5-free-normal_922a030df2d7fccf2c4003375f762404',
    '900' => $fontDir . '/font-awesome-5-free-900_afac1c4a1b37b46ed9e9a33c62d02fa2',
  ),
  'cairo' => array(
    'normal' => $fontDir . '/cairo-normal_068f40925a15c8c667b01b2b55a4b875',
  ),
  'gijgo-material' => array(
    'normal' => $fontDir . '/gijgo-material-normal_243ae49348262c457b957c3f634c1f4a',
  ),
) ?>